//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CECBTIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmn_EmployeeVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cmn_EmployeeVersion()
        {
            this.hrm_EmployeeChangeNAp = new HashSet<hrm_EmployeeChangeNAp>();
            this.hrm_EmployeeEducationalQualifications = new HashSet<hrm_EmployeeEducationalQualifications>();
            this.hrm_EmployeeExtension = new HashSet<hrm_EmployeeExtension>();
            this.hrm_EmployeePosts = new HashSet<hrm_EmployeePosts>();
            this.hrm_EmployeeProfessionalQualifications = new HashSet<hrm_EmployeeProfessionalQualifications>();
            this.hrm_EmployeePromotion = new HashSet<hrm_EmployeePromotion>();
            this.hrm_EmployeeReinstatement = new HashSet<hrm_EmployeeReinstatement>();
            this.hrm_EmployeeReportingAfterLeave = new HashSet<hrm_EmployeeReportingAfterLeave>();
            this.hrm_EmployeeTransfer = new HashSet<hrm_EmployeeTransfer>();
            this.hrm_EmployeeWorkingExperience = new HashSet<hrm_EmployeeWorkingExperience>();
        }
    
        public System.Guid EmployeeVersionId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string EPFNo { get; set; }
        public string Title { get; set; }
        public string NameWithInitial { get; set; }
        public string FullName { get; set; }
        public string NIC { get; set; }
        public Nullable<int> Gender { get; set; }
        public System.Guid WorkSpaceId { get; set; }
        public System.Guid DesignationId { get; set; }
        public Nullable<System.Guid> PhysicalLocationId { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<int> CivilStatus { get; set; }
        public string HomeAddress { get; set; }
        public string ContactAddress { get; set; }
        public string LandphoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string PrivateEmail { get; set; }
        public string NextOfKin { get; set; }
        public string NextOfKinRelationShip { get; set; }
        public string EmployeeRecruitmentType { get; set; }
        public Nullable<System.DateTime> DateOfAppointment { get; set; }
        public string TypeOfContract { get; set; }
        public Nullable<int> DataStatus { get; set; }
        public bool IsActive { get; set; }
        public System.Guid BusinessUnitId { get; set; }
        public System.Guid OrganizationId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.Guid CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<System.Guid> UpdatedUserId { get; set; }
        public string OfficeEmail { get; set; }
        public string PersonalFileNo { get; set; }
        public decimal InitialBasicSalary { get; set; }
        public System.Guid GradeId { get; set; }
        public System.Guid AGMWorkSpaceId { get; set; }
        public Nullable<System.Guid> DGMWorkSpaceId { get; set; }
        public string OfficeEmail2 { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string EmergencyContactNumber2 { get; set; }
        public string EmergencyContactAddress { get; set; }
        public Nullable<System.DateTime> DateOfRetainment { get; set; }
        public Nullable<int> Race { get; set; }
        public int EmpStatus { get; set; }
        public string Initial { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> DateOfExpiry { get; set; }
        public Nullable<System.Guid> DesignationCategoryId { get; set; }
        public Nullable<System.DateTime> IncrementDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeeChangeNAp> hrm_EmployeeChangeNAp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeeEducationalQualifications> hrm_EmployeeEducationalQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeeExtension> hrm_EmployeeExtension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeePosts> hrm_EmployeePosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeeProfessionalQualifications> hrm_EmployeeProfessionalQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeePromotion> hrm_EmployeePromotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeeReinstatement> hrm_EmployeeReinstatement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeeReportingAfterLeave> hrm_EmployeeReportingAfterLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeeTransfer> hrm_EmployeeTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrm_EmployeeWorkingExperience> hrm_EmployeeWorkingExperience { get; set; }
    }
}
