//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CECBTIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmn_EmployeeVersion
    {
        public System.Guid EmployeeVersionId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string EPFNo { get; set; }
        public string Title { get; set; }
        public string NameWithInitial { get; set; }
        public string FullName { get; set; }
        public string NIC { get; set; }
        public Nullable<int> Gender { get; set; }
        public System.Guid WorkSpaceId { get; set; }
        public System.Guid DesignationId { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<int> CivilStatus { get; set; }
        public string HomeAddress { get; set; }
        public string ContactAddress { get; set; }
        public string LandphoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string PrivateEmail { get; set; }
        public string NextOfKin { get; set; }
        public string NextOfKinRelationShip { get; set; }
        public string EmployeeRecruitmentType { get; set; }
        public Nullable<System.DateTime> DateOfAppointment { get; set; }
        public string TypeOfContract { get; set; }
        public Nullable<int> DataStatus { get; set; }
        public bool IsActive { get; set; }
        public System.Guid BusinessUnitId { get; set; }
        public System.Guid OrganizationId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.Guid CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<System.Guid> UpdatedUserId { get; set; }
        public string OfficeEmail { get; set; }
        public string PersonalFileNo { get; set; }
        public decimal InitialBasicSalary { get; set; }
        public Nullable<System.Guid> GradeId { get; set; }
        public System.Guid AGMWorkSpaceId { get; set; }
        public Nullable<System.Guid> DGMWorkSpaceId { get; set; }
        public string OfficeEmail2 { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string EmergencyContactNumber2 { get; set; }
        public string EmergencyContactAddress { get; set; }
        public Nullable<System.DateTime> DateOfRetainment { get; set; }
        public Nullable<int> Race { get; set; }
        public int EmpStatus { get; set; }
        public string Initial { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> DateOfExpiry { get; set; }
        public Nullable<System.Guid> DesignationCategoryId { get; set; }
        public Nullable<System.DateTime> IncrementDate { get; set; }
        public Nullable<System.Guid> SubSectionId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ResignedDate { get; set; }
        public int Version { get; set; }
        public Nullable<System.Guid> PhysicalLocationId { get; set; }
        public string SNameWithInitial { get; set; }
        public string SHomeAddress { get; set; }
    
        public virtual cmn_Employee cmn_Employee { get; set; }
        public virtual hrm_Designation hrm_Designation { get; set; }
        public virtual cmn_WorkSpace cmn_WorkSpace { get; set; }
        public virtual hrm_DesignationCategory hrm_DesignationCategory { get; set; }
        public virtual hrm_Grade hrm_Grade { get; set; }
    }
}
