//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CECBTIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmn_WorkSpaceHistory
    {
        public System.Guid HistoryId { get; set; }
        public System.Guid WorkSpaceId { get; set; }
        public System.Guid OldParentId { get; set; }
        public System.Guid NewParentId { get; set; }
        public System.DateTime EfectiveDate { get; set; }
    }
}
