//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CECBTIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_EmployeePosts
    {
        public System.Guid EmployeeVersionId { get; set; }
        public System.Guid PostId { get; set; }
        public System.DateTime RecievedDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.Guid OrganizationId { get; set; }
        public System.Guid BusinessUnitId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.Guid CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<System.Guid> UpdatedUserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsActing { get; set; }
        public bool IsAttending { get; set; }
        public System.Guid EmpPostId { get; set; }
        public Nullable<System.Guid> EmployeePromotion_PromotionId { get; set; }
        public bool CancelActing { get; set; }
        public bool CancelAttending { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> StartDateActingOrAttending { get; set; }
        public Nullable<System.DateTime> EndDateActingOrAttending { get; set; }
        public Nullable<System.Guid> NoPayLeave_NoPayLeaveId { get; set; }
        public string CencelingReference { get; set; }
    
        public virtual cmn_EmployeeVersion cmn_EmployeeVersion { get; set; }
        public virtual hrm_EmployeePromotion hrm_EmployeePromotion { get; set; }
        public virtual hrm_Post hrm_Post { get; set; }
    }
}
